services:
  grpc1:
    container_name: grpc1
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5001:8888"
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: "1"

networks:
  network0:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK0_SUBNET}